<?php
/**
 * send_email.php
 * --------------
 * Sends a plain-text quiz result report to the student's email address.
 *
 * Uses PHP's built-in mail() function. For production on Azure, replace
 * mail() with PHPMailer + Azure Communication Services SMTP.
 *
 * POST body (JSON):
 *   { to, topMajor, matchPercent, secondMajor, secondPercent, date }
 */

header("Content-Type: application/json");

$input = json_decode(file_get_contents("php://input"), true);

$to           = filter_var(trim($input["to"]           ?? ""), FILTER_VALIDATE_EMAIL);
$topMajor     = htmlspecialchars(trim($input["topMajor"]     ?? ""), ENT_QUOTES);
$matchPercent = (int)($input["matchPercent"]  ?? 0);
$secondMajor  = htmlspecialchars(trim($input["secondMajor"]  ?? ""), ENT_QUOTES);
$secondPercent= (int)($input["secondPercent"] ?? 0);
$date         = htmlspecialchars(trim($input["date"]         ?? ""), ENT_QUOTES);

if (!$to) {
    http_response_code(400);
    echo json_encode(["error" => "Invalid or missing email address."]);
    exit;
}

if (!$topMajor) {
    http_response_code(400);
    echo json_encode(["error" => "No quiz result to send."]);
    exit;
}

$subject = "Your ICT Major Quiz Result — " . $topMajor;

$body = "Hi there,\n\n";
$body .= "Thank you for completing the ICT Pathway Finder quiz!\n\n";
$body .= "Here is a summary of your result:\n";
$body .= "─────────────────────────────────────\n";
$body .= "Recommended Major : " . $topMajor     . " (" . $matchPercent  . "% match)\n";
$body .= "Alternative Match : " . $secondMajor  . " (" . $secondPercent . "% match)\n";
$body .= "Completed         : " . $date         . "\n";
$body .= "─────────────────────────────────────\n\n";
$body .= "What this means for you:\n";
$body .= "Based on your answers, " . $topMajor . " appears to align most closely with ";
$body .= "your interests, strengths, and working style.\n\n";
$body .= "Suggested next steps:\n";
$body .= "• Visit your institution's course guide for more information on this major.\n";
$body .= "• Speak to a course advisor to confirm entry requirements.\n";
$body .= "• Explore free online resources to get a head start in your chosen area.\n\n";
$body .= "This report was generated by the Choose Your Major quiz.\n";
$body .= "If you did not request this, please ignore this email.\n\n";
$body .= "— Choose Your Major Team\n";

$headers  = "From: noreply@chooseyourmajor.example.com\r\n";
$headers .= "Reply-To: noreply@chooseyourmajor.example.com\r\n";
$headers .= "Content-Type: text/plain; charset=UTF-8\r\n";
$headers .= "X-Mailer: PHP/" . phpversion();

$sent = mail($to, $subject, $body, $headers);

if ($sent) {
    echo json_encode(["success" => true]);
} else {
    http_response_code(500);
    echo json_encode(["error" => "mail() failed. Configure SMTP or use PHPMailer for Azure."]);
}
